name: weather
description: A new Flutter project.


publish_to: 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  flutter_weather_icons: ^1.0.2
  geolocator: ^6.1.7
  http: ^0.12.2
  flutter_spinkit: ^4.1.2+1
  intl: ^0.16.1
  firebase_admob: ^0.5.5
  flutter_automation: ^1.4.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

 
  assets:
    - images/BackGround.jpg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
